version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ..:/workspaces/zaplog:cached
    command: sleep infinity
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/zaplog
      JWT_SECRET: devsecret
      NODE_ENV: development
      PORT: 5000
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zaplog
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

